require('dotenv').config();
const { Pool } = require('pg');

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: { rejectUnauthorized: false },
});

const events = [
  // ── FESTIVALS ─────────────────────────────────────────────────────────────
  {
    title_en: 'Wiener Festwochen 2026',
    title_de: 'Wiener Festwochen 2026',
    description_en: "Vienna's prestigious annual arts festival with theater, music, dance and performance. Features 21+ events with free admission across various venues. A highlight of Vienna's cultural calendar.",
    description_de: 'Wiens renommiertes Kunstfestival mit Theater, Musik, Tanz und Performance. Über 21 Veranstaltungen mit freiem Eintritt an verschiedenen Spielstätten.',
    category: 'festival',
    location_name: 'Various venues across Vienna',
    location_address: null,
    district: null,
    start_date: '2026-05-15',
    end_date: '2026-06-21',
    start_time: null,
    end_time: null,
    recurrence: null,
    recurrence_note: null,
    free_type: 'free',
    registration_note_en: null,
    registration_note_de: null,
    external_url: 'https://www.festwochen.at/freier-eintritt',
    image_url: null,
  },
  {
    title_en: 'Kultursommer Wien 2026',
    title_de: 'Kultursommer Wien 2026',
    description_en: 'Free outdoor cultural festival across Vienna\'s neighborhoods. Over 2,000 artists perform at 40+ pop-up stages throughout the city. Music, theater, cabaret, dance, literature, and contemporary circus — all free.',
    description_de: 'Kostenloses Open-Air-Kulturfestival in Wiens Grätzeln. Über 2.000 Künstler:innen auf 40+ Pop-up-Bühnen. Musik, Theater, Kabarett, Tanz, Literatur und Zeitgenössischer Zirkus – alles gratis.',
    category: 'festival',
    location_name: 'Various neighborhoods across Vienna',
    location_address: null,
    district: null,
    start_date: '2026-07-02',
    end_date: '2026-08-16',
    start_time: null,
    end_time: null,
    recurrence: null,
    recurrence_note: null,
    free_type: 'free',
    registration_note_en: null,
    registration_note_de: null,
    external_url: 'https://www.kultursommer.wien',
    image_url: null,
  },
  {
    title_en: 'Donauinselfest 2026',
    title_de: 'Donauinselfest 2026',
    description_en: "Europe's largest free open-air music festival on Vienna's Danube Island. Three days, multiple stages, and hundreds of acts spanning pop, rock, electronic, folk and more. No ticket required — just show up.",
    description_de: 'Europas größtes kostenloses Open-Air-Festival auf der Donauinsel. Drei Tage, viele Bühnen und hunderte Acts aus Pop, Rock, Elektronik, Folk und mehr. Kein Ticket erforderlich.',
    category: 'festival',
    location_name: 'Donauinsel (Danube Island)',
    location_address: 'Donauinsel, 1220 Wien',
    district: 22,
    start_date: '2026-07-03',
    end_date: '2026-07-05',
    start_time: null,
    end_time: null,
    recurrence: null,
    recurrence_note: null,
    free_type: 'free',
    registration_note_en: null,
    registration_note_de: null,
    external_url: 'https://www.donauinselfest.at',
    image_url: null,
  },
  {
    title_en: 'MQ Sommerbühne – Summer Stage at MuseumsQuartier',
    title_de: 'MQ Sommerbühne – MuseumsQuartier',
    description_en: 'Daily free program in the open-air courtyards of MuseumsQuartier. Concerts, talks, performances, film screenings, and literature — something different every evening. Also includes the 25th anniversary celebrations in July.',
    description_de: 'Täglich kostenloses Programm in den Höfen des MuseumsQuartiers. Konzerte, Talks, Performances, Filmvorführungen und Literatur – jeden Abend etwas anderes. Im Juli auch das 25-jährige Jubiläum des MQ.',
    category: 'festival',
    location_name: 'MuseumsQuartier Wien (MQ)',
    location_address: 'Museumsplatz 1, 1070 Wien',
    district: 7,
    start_date: '2026-05-21',
    end_date: '2026-09-06',
    start_time: null,
    end_time: null,
    recurrence: 'daily',
    recurrence_note: 'Daily program — check mqw.at for the specific daily schedule',
    free_type: 'free',
    registration_note_en: null,
    registration_note_de: null,
    external_url: 'https://www.mqw.at',
    image_url: null,
  },

  // ── MUSIC ─────────────────────────────────────────────────────────────────
  {
    title_en: 'Wiener Festwochen Opening – Patti Smith at Heldenplatz',
    title_de: 'Wiener Festwochen Eröffnung – Patti Smith am Heldenplatz',
    description_en: "Free opening concert of the Wiener Festwochen 2026 at Heldenplatz. Features punk pioneer Patti Smith with the Schmusechor and the Festwochen Band Gods Republic. Preceded by the 'Rede an Europa' (Speech to Europe) at Judenplatz.",
    description_de: 'Gratis Eröffnungskonzert der Wiener Festwochen 2026 am Heldenplatz. Mit Punk-Pionierin Patti Smith, dem Schmusechor und der Festwochen-Band Gods Republic. Zuvor die „Rede an Europa" am Judenplatz.',
    category: 'music',
    location_name: 'Heldenplatz',
    location_address: 'Heldenplatz, 1010 Wien',
    district: 1,
    start_date: '2026-05-22',
    end_date: '2026-05-22',
    start_time: null,
    end_time: null,
    recurrence: null,
    recurrence_note: null,
    free_type: 'free',
    registration_note_en: null,
    registration_note_de: null,
    external_url: 'https://www.festwochen.at/freier-eintritt',
    image_url: null,
  },
  {
    title_en: 'Vienna Philharmonic Summer Night Concert',
    title_de: 'Sommernachtkonzert der Wiener Philharmoniker',
    description_en: 'Free open-air concert by the Vienna Philharmonic in the magnificent gardens of Schönbrunn Palace. Conductor: Lorenzo Viotti. Soloist: Bryn Terfel. Gates open around 5pm, concert begins at 8:45pm. Around 100,000 visitors attend on-site and via broadcast.',
    description_de: 'Kostenloses Open-Air-Konzert der Wiener Philharmoniker im Schlosspark Schönbrunn. Dirigent: Lorenzo Viotti. Solist: Bryn Terfel. Einlass ab ca. 17:00 Uhr, Konzertbeginn um 20:45 Uhr.',
    category: 'music',
    location_name: 'Schlosspark Schönbrunn',
    location_address: 'Schönbrunner Schloßstraße 47, 1130 Wien',
    district: 13,
    start_date: '2026-06-19',
    end_date: '2026-06-19',
    start_time: '20:45',
    end_time: null,
    recurrence: null,
    recurrence_note: null,
    free_type: 'free',
    registration_note_en: null,
    registration_note_de: null,
    external_url: 'https://www.wienerphilharmoniker.at/en/summernightconcert',
    image_url: null,
  },

  // ── FILM ──────────────────────────────────────────────────────────────────
  {
    title_en: 'Film Festival Rathausplatz 2026',
    title_de: 'Filmfestival am Rathausplatz 2026',
    description_en: 'Free open-air screenings of opera, ballet, classical music films, and musicals on a giant screen in front of Vienna\'s City Hall. Numerous food stalls from around the world. Open daily from 11am to midnight.',
    description_de: 'Kostenlose Open-Air-Screenings von Oper, Ballett, Klassik und Musicals auf einer Riesenleinwand vor dem Wiener Rathaus. Internationale Speisenstände. Täglich von 11:00 bis 24:00 Uhr geöffnet.',
    category: 'film',
    location_name: 'Rathausplatz',
    location_address: 'Friedrich-Schmidt-Platz 1, 1010 Wien',
    district: 1,
    start_date: '2026-07-04',
    end_date: '2026-09-06',
    start_time: '11:00',
    end_time: '00:00',
    recurrence: 'daily',
    recurrence_note: 'Daily screenings — check filmfestival-rathausplatz.at for the program',
    free_type: 'free',
    registration_note_en: null,
    registration_note_de: null,
    external_url: 'https://filmfestival-rathausplatz.at',
    image_url: null,
  },
  {
    title_en: 'frame[o]ut – Open Air Cinema at MQ',
    title_de: 'frame[o]ut – Open-Air-Kino im MQ',
    description_en: 'Audiovisual open-air film screenings every Friday and Saturday night in the MuseumsQuartier courtyard. Starts at 10pm. Expect art-house surprises under the stars.',
    description_de: 'Open-Air-Filmvorführungen jeden Freitag und Samstag im Hof des MuseumsQuartiers. Beginn um 22:00 Uhr. Arthouse-Überraschungen unter freiem Himmel.',
    category: 'film',
    location_name: 'MuseumsQuartier Wien (MQ)',
    location_address: 'Museumsplatz 1, 1070 Wien',
    district: 7,
    start_date: '2026-07-18',
    end_date: '2026-09-06',
    start_time: '22:00',
    end_time: null,
    recurrence: 'weekly',
    recurrence_note: 'Every Friday and Saturday',
    free_type: 'free',
    registration_note_en: null,
    registration_note_de: null,
    external_url: 'https://www.mqw.at',
    image_url: null,
  },

  // ── DANCE ─────────────────────────────────────────────────────────────────
  {
    title_en: 'ImPulsTanz – Vienna International Dance Festival',
    title_de: 'ImPulsTanz – Wiener Internationales Tanzfestival',
    description_en: 'One of Europe\'s most important contemporary dance festivals. Free events include open showings, jams, and the Public Moves outdoor dance classes. Some performances require a ticket.',
    description_de: 'Eines der bedeutendsten zeitgenössischen Tanzfestivals Europas. Kostenlose Events: Offene Showings, Jams und die Public Moves Outdoor-Tanzkurse. Einige Aufführungen sind kostenpflichtig.',
    category: 'dance',
    location_name: 'Various venues, Vienna',
    location_address: null,
    district: null,
    start_date: '2026-07-09',
    end_date: '2026-08-09',
    start_time: null,
    end_time: null,
    recurrence: null,
    recurrence_note: null,
    free_type: 'free',
    registration_note_en: null,
    registration_note_de: null,
    external_url: 'https://www.impulstanz.com',
    image_url: null,
  },
  {
    title_en: 'Public Moves – Free Outdoor Dance Classes',
    title_de: 'Public Moves – Kostenlose Open-Air-Tanzkurse',
    description_en: "Free outdoor dance classes at parks and public spaces across Vienna, celebrating 10 years of Public Moves. Styles include Afro-Fusion, Breaking, HipHop, House, Waacking and contemporary dance. No registration needed — just show up.",
    description_de: 'Kostenlose Open-Air-Tanzkurse in Parks und öffentlichen Räumen in Wien, zum 10-jährigen Jubiläum von Public Moves. Stile: Afro-Fusion, Breaking, HipHop, House, Waacking, Zeitgenössischer Tanz. Keine Anmeldung erforderlich.',
    category: 'dance',
    location_name: 'Various parks across Vienna (MQ, Schwarzenbergplatz, Seestadt & more)',
    location_address: null,
    district: null,
    start_date: '2026-05-19',
    end_date: '2026-08-31',
    start_time: null,
    end_time: null,
    recurrence: 'weekly',
    recurrence_note: 'Weekly classes at rotating locations — check impulstanz.com/publicmoves for the full schedule',
    free_type: 'free',
    registration_note_en: null,
    registration_note_de: null,
    external_url: 'https://www.impulstanz.com/en/publicmoves/',
    image_url: null,
  },

  // ── THEATER ───────────────────────────────────────────────────────────────
  {
    title_en: 'Theater im Park – Belvedere Gardens',
    title_de: 'Theater im Park – Belvedere',
    description_en: "Free open-air performances in the beautiful gardens of Belvedere Palace: theater, cabaret, musicals, concerts, readings, philosophical discussions and children's events. Opens with Michael Niavarani's cabaret show.",
    description_de: 'Kostenlose Open-Air-Aufführungen in den Gärten des Belvedere: Theater, Kabarett, Musicals, Konzerte, Lesungen, Philosophie und Kinderevents. Eröffnung mit Michael Niavaranis Kabarettshow.',
    category: 'theater',
    location_name: 'Belvedere Palace Gardens',
    location_address: 'Prinz-Eugen-Straße 27, 1030 Wien',
    district: 3,
    start_date: '2026-05-20',
    end_date: '2026-09-19',
    start_time: null,
    end_time: null,
    recurrence: null,
    recurrence_note: 'Program varies — check the Belvedere website for the schedule',
    free_type: 'free',
    registration_note_en: null,
    registration_note_de: null,
    external_url: 'https://www.belvedere.at',
    image_url: null,
  },
  {
    title_en: 'Wiener Kabarettfestival 2026',
    title_de: 'Wiener Kabarettfestival 2026',
    description_en: 'Vienna\'s annual cabaret festival with performances by Austrian and international comedians. Check the official website for specific free or discounted events.',
    description_de: 'Wiens jährliches Kabarettfestival mit Auftritten österreichischer und internationaler Kabarettist:innen. Website für kostenlose oder ermäßigte Veranstaltungen prüfen.',
    category: 'theater',
    location_name: 'Various venues, Vienna',
    location_address: null,
    district: null,
    start_date: '2026-07-25',
    end_date: '2026-07-27',
    start_time: null,
    end_time: null,
    recurrence: null,
    recurrence_note: null,
    free_type: 'free_with_registration',
    registration_note_en: 'Some performances are free — check wienerkabarettfestival.at for the program and free events',
    registration_note_de: 'Einige Veranstaltungen sind kostenlos – Programm auf wienerkabarettfestival.at prüfen',
    external_url: 'https://wienerkabarettfestival.at',
    image_url: null,
  },

  // ── SPORT ─────────────────────────────────────────────────────────────────
  {
    title_en: 'Bewegt im Park – Free Sports & Fitness in Vienna\'s Parks',
    title_de: 'Bewegt im Park – Kostenlose Sport- und Fitnesskurse',
    description_en: "Austria's largest free movement initiative. Professional trainers lead free fitness classes in parks across Vienna: yoga, back fitness, tai chi, zumba, football, beach volleyball and more. No registration needed — just show up.",
    description_de: 'Österreichs größte kostenlose Bewegungsinitiative. Professionelle Trainer:innen leiten Kurse in Parks in ganz Wien: Yoga, Rückenfit, Tai Chi, Zumba, Fußball, Beachvolleyball und mehr. Keine Anmeldung erforderlich.',
    category: 'sport',
    location_name: 'Parks and open spaces across Vienna',
    location_address: null,
    district: null,
    start_date: '2026-06-01',
    end_date: '2026-09-30',
    start_time: null,
    end_time: null,
    recurrence: 'daily',
    recurrence_note: 'Classes run daily at fixed park locations — find your nearest one at bewegt-im-park.at',
    free_type: 'free',
    registration_note_en: null,
    registration_note_de: null,
    external_url: 'https://www.bewegt-im-park.at/bundesland/wien/',
    image_url: null,
  },

  // ── LITERATURE ────────────────────────────────────────────────────────────
  {
    title_en: 'O-Töne – Open Air Literature Festival',
    title_de: 'O-Töne – Open-Air-Literaturfestival',
    description_en: 'High-caliber outdoor readings every Thursday evening at MuseumsQuartier. Contemporary Austrian and international literature under open skies. One of Vienna\'s most beloved summer literary traditions.',
    description_de: 'Hochkarätige Open-Air-Lesungen jeden Donnerstagabend im MuseumsQuartier. Österreichische und internationale Gegenwartsliteratur unter freiem Himmel. Eine der beliebtesten Sommerliteraturtradition Wiens.',
    category: 'literature',
    location_name: 'MuseumsQuartier Wien (MQ)',
    location_address: 'Museumsplatz 1, 1070 Wien',
    district: 7,
    start_date: '2026-07-09',
    end_date: '2026-08-27',
    start_time: '20:00',
    end_time: null,
    recurrence: 'weekly',
    recurrence_note: 'Every Thursday evening',
    free_type: 'free',
    registration_note_en: null,
    registration_note_de: null,
    external_url: 'https://www.mqw.at',
    image_url: null,
  },
  {
    title_en: 'Wiener Festwochen – Free Readings & Talks',
    title_de: 'Wiener Festwochen – Kostenlose Lesungen & Talks',
    description_en: "The Wiener Festwochen's House and Club of the Republic on the Badeschiff (Danube Canal) hosts free talks, readings and events for all ages every Wednesday to Sunday throughout the festival.",
    description_de: 'Das Haus und der Club der Republik auf dem Badeschiff am Donaukanal bietet im Rahmen der Festwochen mittwochs bis sonntags kostenlose Talks, Lesungen und Veranstaltungen für alle Altersgruppen.',
    category: 'literature',
    location_name: 'Badeschiff Wien (Donaukanal)',
    location_address: 'Donaukanal, 1010 Wien',
    district: 1,
    start_date: '2026-05-20',
    end_date: '2026-06-21',
    start_time: null,
    end_time: null,
    recurrence: 'weekly',
    recurrence_note: 'Wednesday to Sunday throughout the Festwochen period',
    free_type: 'free',
    registration_note_en: null,
    registration_note_de: null,
    external_url: 'https://www.festwochen.at/freier-eintritt',
    image_url: null,
  },
];

async function seed() {
  const client = await pool.connect();
  try {
    console.log(`Seeding ${events.length} events...`);
    let inserted = 0;

    for (const e of events) {
      await client.query(
        `INSERT INTO events (
          title_en, title_de, description_en, description_de,
          category, location_name, location_address, district,
          start_date, end_date, start_time, end_time,
          recurrence, recurrence_note,
          free_type, registration_note_en, registration_note_de,
          external_url, image_url
        ) VALUES (
          $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19
        ) ON CONFLICT DO NOTHING`,
        [
          e.title_en, e.title_de, e.description_en, e.description_de,
          e.category, e.location_name, e.location_address, e.district,
          e.start_date, e.end_date, e.start_time, e.end_time,
          e.recurrence, e.recurrence_note,
          e.free_type, e.registration_note_en, e.registration_note_de,
          e.external_url, e.image_url,
        ]
      );
      inserted++;
      console.log(`  ✓ ${e.title_en}`);
    }

    console.log(`\nDone! ${inserted} events seeded.`);
  } finally {
    client.release();
    await pool.end();
  }
}

seed().catch(err => { console.error(err); process.exit(1); });
