require('dotenv').config();
const { Pool } = require('pg');
const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });

const newEvents = [
  // ── from docx: May events ───────────────────────────────────────────────
  {
    title_en: '#wienliebe Festival 2026',
    title_de: '#wienliebe Festival 2026',
    description_en: 'A free community festival at Rathausplatz celebrating Vienna and its people. Music, food, activities and a great atmosphere in the heart of the city.',
    description_de: 'Ein kostenloses Community-Festival am Rathausplatz – Musik, Essen, Aktivitäten und gute Stimmung im Herzen der Stadt.',
    category: 'community',
    location_name: 'Rathausplatz',
    location_address: 'Friedrich-Schmidt-Platz 1, 1010 Wien',
    district: 1,
    start_date: '2026-05-23',
    end_date: '2026-05-25',
    start_time: null, end_time: null, recurrence: null, recurrence_note: null,
    free_type: 'free',
    registration_note_en: null, registration_note_de: null,
    external_url: 'https://www.wien.gv.at',
    image_url: null,
  },
  {
    title_en: 'Upper Austria Days at Heldenplatz',
    title_de: 'Oberösterreich-Tage am Heldenplatz',
    description_en: 'Free open-air event at Heldenplatz showcasing Upper Austrian culture, food, music and traditions. A popular community gathering in the centre of Vienna.',
    description_de: 'Kostenloses Open-Air-Event am Heldenplatz mit oberösterreichischer Kultur, Kulinarik, Musik und Traditionen.',
    category: 'community',
    location_name: 'Heldenplatz',
    location_address: 'Heldenplatz, 1010 Wien',
    district: 1,
    start_date: '2026-05-29',
    end_date: '2026-05-30',
    start_time: null, end_time: null, recurrence: null, recurrence_note: null,
    free_type: 'free',
    registration_note_en: null, registration_note_de: null,
    external_url: 'https://www.wien.info',
    image_url: null,
  },
  {
    title_en: 'Long Night of the Churches',
    title_de: 'Lange Nacht der Kirchen',
    description_en: 'One night a year, hundreds of churches across Vienna open their doors for free events: concerts, art installations, talks, guided tours and contemplative spaces. A unique cultural experience.',
    description_de: 'Eine Nacht im Jahr öffnen hunderte Kirchen in Wien für kostenlose Veranstaltungen: Konzerte, Kunst, Talks, Führungen und Stille. Ein einzigartiges Kulturerlebnis.',
    category: 'community',
    location_name: 'Churches citywide, Vienna',
    location_address: null,
    district: null,
    start_date: '2026-05-29',
    end_date: '2026-05-29',
    start_time: '18:00', end_time: '01:00', recurrence: null, recurrence_note: null,
    free_type: 'free',
    registration_note_en: null, registration_note_de: null,
    external_url: 'https://langenachtderkirchen.at',
    image_url: null,
  },
  {
    title_en: 'Vienna Shorts Film Festival – Free Screenings',
    title_de: 'Vienna Shorts – Kostenlose Filmvorführungen',
    description_en: 'International short film festival with selected free screenings at various Vienna venues. Check the program for which specific screenings have free admission.',
    description_de: 'Internationales Kurzfilmfestival mit ausgewählten kostenlosen Vorführungen in Wien. Programm auf Gratis-Vorstellungen prüfen.',
    category: 'film',
    location_name: 'Various venues, Vienna',
    location_address: null,
    district: null,
    start_date: '2026-05-26',
    end_date: '2026-05-31',
    start_time: null, end_time: null, recurrence: null, recurrence_note: null,
    free_type: 'free_with_registration',
    registration_note_en: 'Only selected screenings are free — check viennashorts.com for the free program',
    registration_note_de: 'Nur ausgewählte Vorführungen sind kostenlos – Gratis-Programm auf viennashorts.com prüfen',
    external_url: 'https://www.viennashorts.com',
    image_url: null,
  },
  {
    title_en: "Women's Run Vienna – Free for Spectators",
    title_de: 'Österreichischer Frauenlauf – Zuschauer kostenlos',
    description_en: "Europe's largest women's run through Vienna's Prater. Free to watch from the sidelines — a great atmosphere and an inspiring event.",
    description_de: 'Europas größter Frauenlauf durch den Wiener Prater. Zuschauen ist kostenlos – tolle Stimmung und ein inspirierendes Event.',
    category: 'sport',
    location_name: 'Prater, Vienna',
    location_address: 'Prater, 1020 Wien',
    district: 2,
    start_date: '2026-05-31',
    end_date: '2026-05-31',
    start_time: null, end_time: null, recurrence: null, recurrence_note: null,
    free_type: 'free',
    registration_note_en: 'Free for spectators — registration required to participate in the run',
    registration_note_de: 'Zuschauen kostenlos – Anmeldung nur für Teilnehmerinnen erforderlich',
    external_url: 'https://www.frauenlauf.at',
    image_url: null,
  },

  // ── from docx: June events ───────────────────────────────────────────────
  {
    title_en: 'Sport Austria Finals – Free for Spectators',
    title_de: 'Sport Austria Finals – Zuschauer kostenlos',
    description_en: "Austria's biggest multi-sport event with finals across many disciplines. Free admission for spectators at most venues — check the program for which events are open to the public.",
    description_de: 'Österreichs größtes Multi-Sport-Event mit Finals in vielen Disziplinen. Eintritt für Zuschauer:innen an den meisten Veranstaltungsorten kostenlos.',
    category: 'sport',
    location_name: 'Various venues, Vienna',
    location_address: null,
    district: null,
    start_date: '2026-06-03',
    end_date: '2026-06-07',
    start_time: null, end_time: null, recurrence: null, recurrence_note: null,
    free_type: 'free',
    registration_note_en: 'Most finals are free for spectators — check sportaustria.at for the schedule',
    registration_note_de: 'Die meisten Finals sind für Zuschauer:innen kostenlos – Programm auf sportaustria.at',
    external_url: 'https://www.sportaustria.at',
    image_url: null,
  },
  {
    title_en: 'Science Fiction im Park – VOLXkino',
    title_de: 'Science Fiction im Park – VOLXkino',
    description_en: 'Free open-air sci-fi film screenings in Vienna parks, presented by VOLXkino. Bring a blanket, enjoy cinema under the stars.',
    description_de: 'Kostenlose Open-Air-SciFi-Filmvorführungen in Wiener Parks, präsentiert von VOLXkino. Decke mitbringen und Kino unterm Sternenhimmel genießen.',
    category: 'film',
    location_name: 'Parks across Vienna (locations TBC)',
    location_address: null,
    district: null,
    start_date: '2026-06-09',
    end_date: '2026-06-14',
    start_time: '21:00', end_time: null, recurrence: null, recurrence_note: null,
    free_type: 'free',
    registration_note_en: null, registration_note_de: null,
    external_url: 'https://www.volxkino.at',
    image_url: null,
  },
  {
    title_en: 'Rainbow Parade – Vienna Pride 2026',
    title_de: 'Regenbogenparade – Vienna Pride 2026',
    description_en: "Vienna's iconic Rainbow Parade on the Ringstrasse celebrating its 30th anniversary. Over 300,000 participants expected. The parade sets off at noon and circles the entire Ringstrasse. Free Pride Village at Rathausplatz from 6:30pm.",
    description_de: 'Wiens ikonische Regenbogenparade auf der Ringstrasse feiert ihr 30-jähriges Jubiläum. Über 300.000 Teilnehmer:innen erwartet. Start um 12:00 Uhr, Umzug rund um die Ringstrasse. Kostenloses Pride Village am Rathausplatz ab 18:30 Uhr.',
    category: 'community',
    location_name: 'Ringstrasse (start) → Rathausplatz',
    location_address: 'Ringstrasse, 1010 Wien',
    district: 1,
    start_date: '2026-06-13',
    end_date: '2026-06-13',
    start_time: '12:00', end_time: null, recurrence: null, recurrence_note: null,
    free_type: 'free',
    registration_note_en: null, registration_note_de: null,
    external_url: 'https://viennapride.at',
    image_url: null,
  },

  // ── VOLXkino full summer ─────────────────────────────────────────────────
  {
    title_en: 'VOLXkino – Free Open Air Cinema',
    title_de: 'VOLXkino – Kostenloses Open-Air-Kino',
    description_en: "Vienna's beloved wandering cinema for 35 years. Over 40 free outdoor film screenings in parks, courtyards and public spaces across the city every summer. Also includes Sunset Cinema for younger audiences (Jun 26 – Sep 3).",
    description_de: 'Wiens geliebtes Wanderkino seit 35 Jahren. Über 40 kostenlose Filmvorführungen im Freien in Parks, Innenhöfen und öffentlichen Räumen der Stadt. Inkl. Sunset Cinema für jüngeres Publikum (26. Jun – 3. Sep).',
    category: 'film',
    location_name: 'Various parks and outdoor spaces across Vienna',
    location_address: null,
    district: null,
    start_date: '2026-06-10',
    end_date: '2026-09-19',
    start_time: null, end_time: null,
    recurrence: 'weekly',
    recurrence_note: 'Multiple screenings per week at rotating locations — check volxkino.at for the full schedule',
    free_type: 'free',
    registration_note_en: null, registration_note_de: null,
    external_url: 'https://www.volxkino.at',
    image_url: null,
  },

  // ── more summer events ───────────────────────────────────────────────────
  {
    title_en: 'Summerstage – Open Air at Donaukanal',
    title_de: 'Summerstage – Open Air am Donaukanal',
    description_en: "Vienna's most popular open-air venue on the Danube Canal, running all summer. Free concerts, DJ sets, readings and art exhibitions. Some headline events are ticketed — the daily bar and many concerts are free.",
    description_de: 'Wiens beliebteste Open-Air-Location am Donaukanal für den ganzen Sommer. Kostenlose Konzerte, DJ-Sets, Lesungen und Kunstausstellungen. Einige Hauptevents kostenpflichtig – tägliche Bar und viele Konzerte kostenlos.',
    category: 'music',
    location_name: 'Summerstage, Donaukanal',
    location_address: 'Roßauer Lände 4, 1090 Wien',
    district: 9,
    start_date: '2026-05-01',
    end_date: '2026-09-30',
    start_time: null, end_time: null,
    recurrence: 'daily',
    recurrence_note: 'Open daily — free concerts on most days, check summerstage.at for ticketed headliners',
    free_type: 'free_with_registration',
    registration_note_en: 'Most concerts are free — check summerstage.at for which events require tickets',
    registration_note_de: 'Die meisten Konzerte sind kostenlos – summerstage.at für kostenpflichtige Events prüfen',
    external_url: 'https://www.summerstage.at',
    image_url: null,
  },
  {
    title_en: 'Afrika Tage Wien 2026',
    title_de: 'Afrika Tage Wien 2026',
    description_en: 'One of Europe\'s largest African cultural festivals, held in the Prater. Free admission. Music from across the African continent, food, crafts, dance and cultural programmes. A vibrant celebration of African cultures.',
    description_de: 'Eines der größten afrikanischen Kulturfestivals Europas im Prater. Eintritt kostenlos. Musik vom gesamten afrikanischen Kontinent, Essen, Kunsthandwerk, Tanz und Kulturprogramm.',
    category: 'festival',
    location_name: 'Prater (Jesuitenwiese)',
    location_address: 'Jesuitenwiese, 1020 Wien',
    district: 2,
    start_date: '2026-08-14',
    end_date: '2026-08-24',
    start_time: null, end_time: null, recurrence: null, recurrence_note: null,
    free_type: 'free',
    registration_note_en: null, registration_note_de: null,
    external_url: 'https://www.afrikatage.at',
    image_url: null,
  },
  {
    title_en: 'Buskers Festival Vienna',
    title_de: 'Buskers Festival Wien',
    description_en: 'International street performers take over Vienna\'s public spaces: acrobats, musicians, comedians, magicians and more. Completely free — just bring coins to tip your favourites.',
    description_de: 'Internationale Straßenkünstler:innen bevölkern Wiens öffentliche Räume: Akrobatik, Musik, Comedy, Zauberei und mehr. Komplett kostenlos – Kleingeld zum Applaudieren mitbringen.',
    category: 'festival',
    location_name: 'Various public spaces, Vienna city centre',
    location_address: null,
    district: null,
    start_date: '2026-09-01',
    end_date: '2026-09-06',
    start_time: null, end_time: null, recurrence: null, recurrence_note: null,
    free_type: 'free',
    registration_note_en: null, registration_note_de: null,
    external_url: 'https://www.buskers.at',
    image_url: null,
  },
  {
    title_en: 'European Heritage Days – Open Monument Day',
    title_de: 'Europäischer Tag des offenen Denkmals',
    description_en: 'Once a year, historic buildings, palaces, archives, government buildings and private estates that are normally closed open their doors for free guided tours and exhibitions. One of the best days to explore hidden Vienna.',
    description_de: 'Einmal jährlich öffnen historische Gebäude, Paläste, Archive, Amtsgebäude und private Anwesen, die normalerweise geschlossen sind, ihre Türen für kostenlose Führungen und Ausstellungen. Einer der besten Tage, um verstecktes Wien zu erkunden.',
    category: 'community',
    location_name: 'Historic buildings citywide, Vienna',
    location_address: null,
    district: null,
    start_date: '2026-09-27',
    end_date: '2026-09-27',
    start_time: null, end_time: null, recurrence: null, recurrence_note: null,
    free_type: 'free',
    registration_note_en: null, registration_note_de: null,
    external_url: 'https://www.bda.gv.at',
    image_url: null,
  },
];

async function seed() {
  const client = await pool.connect();
  try {
    console.log(`Seeding ${newEvents.length} new events...`);
    for (const e of newEvents) {
      await client.query(
        `INSERT INTO events (
          title_en, title_de, description_en, description_de,
          category, location_name, location_address, district,
          start_date, end_date, start_time, end_time,
          recurrence, recurrence_note,
          free_type, registration_note_en, registration_note_de,
          external_url, image_url
        ) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19)
        ON CONFLICT DO NOTHING`,
        [
          e.title_en, e.title_de, e.description_en, e.description_de,
          e.category, e.location_name, e.location_address, e.district,
          e.start_date, e.end_date, e.start_time, e.end_time,
          e.recurrence, e.recurrence_note,
          e.free_type, e.registration_note_en, e.registration_note_de,
          e.external_url, e.image_url,
        ]
      );
      console.log(`  ✓ ${e.title_en}`);
    }
    console.log(`\nDone!`);
  } finally {
    client.release();
    await pool.end();
  }
}

seed().catch(e => { console.error(e); process.exit(1); });
